language: python
python:
  - "3.6"
  # command to install dependencies
services:
  - docker
before_script: pip install docker-compose

script:
  - docker-compose run app sh -c "python manage.py test "
  - docker-compose run app sh -c "python manage.py flake8"

