language: python
python:
  - "3.6"
  # command to install dependencies
services:
  - docker
before_script: pip install docker-compose

script:
  - docker-compose run --rm app sh -c "python manage.py test && flake8"


